services:
  todo-app:
    depends_on:
      mongodb:
        condition: service_started
    image: mohsenrezaei89/todo-app:latest
    build:
      context: .
    ports:
      - 8080:8080
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=tododb'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "'printjson(db.runCommand({ ping: 1 }))'" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 27017:27017